plugins { id 'com.android.application' }
android {
    namespace 'com.burp.burp.iwillsuckyauprealgoosimgonnasuckyauprealtight.burp'
    compileSdk 34
    defaultConfig {
        applicationId "com.burp.burp.iwillsuckyauprealgoosimgonnasuckyauprealtight.burp"
        minSdk 21
        targetSdk 34
    }
}
