plugins {
    id 'com.android.application'
}

android {
    namespace 'com.burp.burp.iwillsuckyauprealgoosimgonnasuckyauprealtight.burp'
    compileSdkVersion 34

    defaultConfig {
        applicationId "com.burp.burp.iwillsuckyauprealgoosimgonnasuckyauprealtight.burp"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
    }
}
